#!/usr/bin/env python3

from fastapi import FastAPI, Request, Form, HTTPException, Depends, Response
from fastapi.responses import HTMLResponse, JSONResponse, RedirectResponse
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
import sqlite3
import os
import hashlib
import binascii
import time
import jwt
import hmac
from typing import Optional

# ---------- Config ----------
DB_PATH = "users.db"
JWT_SECRET = os.environ.get("JWT_SECRET", "change-this-secret-now")
JWT_ALGORITHM = "HS256"
JWT_EXP_SECONDS = 60 * 30

HASH_NAME = "sha256"
PBKDF2_ITERATIONS = 100_000
SALT_SIZE = 16

app = FastAPI(title="FastAPI Auth UI")

# ---------- Database ----------
def get_db():
    conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
            return conn

            def init_db():
                db = get_db()
                    db.execute("""
                            CREATE TABLE IF NOT EXISTS users (
                                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                                                    username TEXT UNIQUE NOT NULL,
                                                                salt TEXT NOT NULL,
                                                                            pwd_hash TEXT NOT NULL,
                                                                                        created_at INTEGER NOT NULL
                                                                                                )
                                                                                                    """)
                                                                                                        db.commit()
                                                                                                            db.close()

                                                                                                            init_db()

                                                                                                            # ---------- Password ----------
                                                                                                            def gen_salt():
                                                                                                                return os.urandom(SALT_SIZE)

                                                                                                                def hash_password(password, salt):
                                                                                                                    return hashlib.pbkdf2_hmac(HASH_NAME, password.encode(), salt, PBKDF2_ITERATIONS)

                                                                                                                    def hex_encode(b): return binascii.hexlify(b).decode()
                                                                                                                    def hex_decode(s): return binascii.unhexlify(s.encode())

                                                                                                                    def create_user(username, password):
                                                                                                                        salt = gen_salt()
                                                                                                                            h = hash_password(password, salt)
                                                                                                                                db = get_db()
                                                                                                                                    try:
                                                                                                                                            db.execute(
                                                                                                                                                        "INSERT INTO users (username, salt, pwd_hash, created_at) VALUES (?, ?, ?, ?)",
                                                                                                                                                                    (username, hex_encode(salt), hex_encode(h), int(time.time()))
                                                                                                                                                                            )
                                                                                                                                                                                    db.commit()
                                                                                                                                                                                        except sqlite3.IntegrityError:
                                                                                                                                                                                                raise ValueError("User exists")
                                                                                                                                                                                                    finally:
                                                                                                                                                                                                            db.close()

                                                                                                                                                                                                            def get_user(username):
                                                                                                                                                                                                                db = get_db()
                                                                                                                                                                                                                    user = db.execute("SELECT * FROM users WHERE username=?", (username,)).fetchone()
                                                                                                                                                                                                                        db.close()
                                                                                                                                                                                                                            return user

                                                                                                                                                                                                                            def verify_password(stored_hash, stored_salt, password):
                                                                                                                                                                                                                                calc = hash_password(password, hex_decode(stored_salt))
                                                                                                                                                                                                                                    return hmac.compare_digest(hex_decode(stored_hash), calc)

                                                                                                                                                                                                                                    # ---------- JWT ----------
                                                                                                                                                                                                                                    def create_token(username):
                                                                                                                                                                                                                                        payload = {
                                                                                                                                                                                                                                                "sub": username,
                                                                                                                                                                                                                                                        "exp": int(time.time()) + JWT_EXP_SECONDS,
                                                                                                                                                                                                                                                                "iat": int(time.time())
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                        return jwt.encode(payload, JWT_SECRET, algorithm=JWT_ALGORITHM)

                                                                                                                                                                                                                                                                        def decode_token(token):
                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                    return jwt.decode(token, JWT_SECRET, algorithms=[JWT_ALGORITHM])
                                                                                                                                                                                                                                                                                        except jwt.ExpiredSignatureError:
                                                                                                                                                                                                                                                                                                raise HTTPException(401, "Token expired")
                                                                                                                                                                                                                                                                                                    except jwt.InvalidTokenError:
                                                                                                                                                                                                                                                                                                            raise HTTPException(401, "Invalid token")

                                                                                                                                                                                                                                                                                                            # ---------- Auth Dependency ----------
                                                                                                                                                                                                                                                                                                            bearer = HTTPBearer(auto_error=False)

                                                                                                                                                                                                                                                                                                            async def get_current_user(request: Request, creds: Optional[HTTPAuthorizationCredentials] = Depends(bearer)):
                                                                                                                                                                                                                                                                                                                token = creds.credentials if creds else request.cookies.get("access_token")
                                                                                                                                                                                                                                                                                                                    if not token:
                                                                                                                                                                                                                                                                                                                            raise HTTPException(401)
                                                                                                                                                                                                                                                                                                                                payload = decode_token(token)
                                                                                                                                                                                                                                                                                                                                    user = get_user(payload["sub"])
                                                                                                                                                                                                                                                                                                                                        if not user:
                                                                                                                                                                                                                                                                                                                                                raise HTTPException(401)
                                                                                                                                                                                                                                                                                                                                                    return user

                                                                                                                                                                                                                                                                                                                                                    # ---------- UI Styling ----------
                                                                                                                                                                                                                                                                                                                                                    BASE_HTML = """
                                                                                                                                                                                                                                                                                                                                                    <!doctype html>
                                                                                                                                                                                                                                                                                                                                                    <html>
                                                                                                                                                                                                                                                                                                                                                    <head>
                                                                                                                                                                                                                                                                                                                                                    <title>FastAPI Auth</title>
                                                                                                                                                                                                                                                                                                                                                    <style>
                                                                                                                                                                                                                                                                                                                                                    body {
                                                                                                                                                                                                                                                                                                                                                        margin: 0;
                                                                                                                                                                                                                                                                                                                                                            background: linear-gradient(120deg, #4f46e5, #0ea5e9);
                                                                                                                                                                                                                                                                                                                                                                font-family: Arial, sans-serif;
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                .card {
                                                                                                                                                                                                                                                                                                                                                                    background: white;
                                                                                                                                                                                                                                                                                                                                                                        width: 100%%;
                                                                                                                                                                                                                                                                                                                                                                            max-width: 380px;
                                                                                                                                                                                                                                                                                                                                                                                margin: 10vh auto;
                                                                                                                                                                                                                                                                                                                                                                                    padding: 30px;
                                                                                                                                                                                                                                                                                                                                                                                        border-radius: 12px;
                                                                                                                                                                                                                                                                                                                                                                                            box-shadow: 0 10px 30px rgba(0,0,0,.2);
                                                                                                                                                                                                                                                                                                                                                                                                text-align: center;
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                h2 {
                                                                                                                                                                                                                                                                                                                                                                                                    margin-bottom: 20px;
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                    input {
                                                                                                                                                                                                                                                                                                                                                                                                        width: 100%%;
                                                                                                                                                                                                                                                                                                                                                                                                            padding: 12px;
                                                                                                                                                                                                                                                                                                                                                                                                                margin: 8px 0;
                                                                                                                                                                                                                                                                                                                                                                                                                    border-radius: 6px;
                                                                                                                                                                                                                                                                                                                                                                                                                        border: 1px solid #ddd;
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                        button {
                                                                                                                                                                                                                                                                                                                                                                                                                            width: 100%%;
                                                                                                                                                                                                                                                                                                                                                                                                                                padding: 12px;
                                                                                                                                                                                                                                                                                                                                                                                                                                    border: none;
                                                                                                                                                                                                                                                                                                                                                                                                                                        border-radius: 6px;
                                                                                                                                                                                                                                                                                                                                                                                                                                            background: #4f46e5;
                                                                                                                                                                                                                                                                                                                                                                                                                                                color: white;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    font-weight: bold;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursor: pointer;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        button:hover {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: #4338ca;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            a {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                display: block;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    margin-top: 12px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: #4f46e5;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            text-decoration: none;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .error {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: red;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    margin-bottom: 10px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .success {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: green;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </head>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        %s
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # ---------- Routes ----------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @app.get("/", response_class=HTMLResponse)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async def home():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return HTMLResponse(BASE_HTML % """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2>FastAPI Auth</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="/signup">Create Account</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="/login">Login</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="/protected">Dashboard</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @app.get("/signup", response_class=HTMLResponse)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                async def signup_form():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return HTMLResponse(BASE_HTML % """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2>Sign Up</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <form method="post">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input name="username" placeholder="Username" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input name="password" type="password" placeholder="Password" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button>Create Account</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="/login">Already have an account?</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @app.post("/signup", response_class=HTMLResponse)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async def signup(username: str = Form(...), password: str = Form(...)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        create_user(username.strip(), password)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return HTMLResponse(BASE_HTML % """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 class="success">Account Created!</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="/login">Login Now</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except ValueError:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return HTMLResponse(BASE_HTML % """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2>Sign Up</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p class="error">Username already taken</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="/signup">Try again</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @app.get("/login", response_class=HTMLResponse)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async def login_form():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return HTMLResponse(BASE_HTML % """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2>Login</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <form method="post">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input name="username" placeholder="Username" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input name="password" type="password" placeholder="Password" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button>Login</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="/signup">Create account</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @app.post("/login")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async def login(response: Response, username: str = Form(...), password: str = Form(...)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        user = get_user(username.strip())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not user or not verify_password(user["pwd_hash"], user["salt"], password):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return HTMLResponse(BASE_HTML % """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 class="error">Invalid Login</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="/login">Try Again</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        token = create_token(username)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res = RedirectResponse("/protected", status_code=303)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.set_cookie("access_token", token, httponly=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @app.get("/protected", response_class=HTMLResponse)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async def dashboard(user=Depends(get_current_user)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return HTMLResponse(BASE_HTML % f"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2>Dashboard</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Welcome, <b>{user['username']}</b></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="/me">View Profile JSON</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="/logout">Logout</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @app.get("/me")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async def me(user=Depends(get_current_user)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return dict(user)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @app.get("/logout")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                async def logout():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res = RedirectResponse("/", status_code=303)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.delete_cookie("access_token")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return res